Repository pivotal-cf/docs-pcf-windows, pull requests merged in 2019-10, with the labels that each got.

#59 Removing the GoRouter to Windows Container TLS limitation
  docs-content/architecture.html.md.erb
Labels: in progress

#61 Revert notice of windows2016 stack removal
  docs-content/migrating.html.md.erb
Labels: unscheduled

#62 Add notes about PAS mTLS and disabling TCP routing
  docs-content/installing.html.md.erb
Labels: scheduled
