Repository pivotal-cf/docs-pcf-windows, pull requests merged in 2019-08, with the labels that each got.

#52 Removed references to Azure
  docs-content/smb-volumes-apps.html.md.erb
Labels: scheduled

#51 Removed Azure and 1709/1803 references
  docs-content/smb-volumes-apps.html.md.erb
Labels: scheduled

#50 Add docs for enable route integrity beta feature for 2.7
  docs-content/images/enable-tls.png
  docs-content/installing.html.md.erb
Labels: delivered

#53 fixed % typo with SMB ENV variable
  docs-content/smb-volumes-apps.html.md.erb
Labels: in progress

#58 Windows: A note about the legacy windows2016 stack
  docs-content/migrating.html.md.erb
Labels: scheduled
